jpask1392/jamiepask-devstore.myshopify.com@production/build:
  - source: .github/workflows/automerge.yml
    dest: .github/workflows/automerge.yml
  - source: shopify/assets/
    dest: assets/
  - source: shopify/config/
    dest: config/
  - source: shopify/locales/
    dest: locales/ 
  - source: shopify/sections/
    dest: sections/ 
  - source: shopify/snippets/
    dest: snippets/ 
  - source: shopify/templates/
    dest: templates/
    